### ISSUE TITLE
App.css, app.css paths have collided

### ISSUE THREAD

**Issue by jerrythomas** [rixo/svench#25]
When cloning the repo on a case insensitive file system I am getting this error. 

warning: the following paths have collided (e.g. case-sensitive paths on a case-insensitive filesystem) and only one from the same colliding group is in the working tree:

  'src/themes/default/app/App.css'
  'src/themes/default/app/app.css'

Can we change one of the names so that the names don't collide?

**Comment by rixo** [comment]
Hey!

This should already be fixed on `next` branch: https://github.com/rixo/svench/pull/20

If you intend to do anything with Svench, you should at least use the `next` branch. It's way ahead of master.

It's not even the tip actually, there's a diverged branch and some things I need to commit on my machine centered around integration with Snowpack & Vite, and a cli tool. It's been going well, it's surely becoming the next master...

Anyway, may I ask if you have any special idea in mind for digging in this code?

**Comment by dipscom** [comment]
Hi Jerry,

This issue has also now been fixed in the main branch. Do you want to check and let us know if your issue has been solved?

**Comment by rixo** [comment]
Fixed on `main` branch. Feel free to reopen if you still have the problem.
