### ISSUE TITLE
customizing css classes for View Component

### ISSUE THREAD

**Issue by bhvngt** [rixo/svench#37]
I bumped into this use case where I was trying to make the `width 100%` for my component container. This requires parent container to be also set to `width 100%`. Would it make sense to expose and override the class of `View` component so that such use cases can be addressed by passing classes to the `View Component`. I am attaching a screenshot for your ref.

![image](https://user-images.githubusercontent.com/79074469/127976516-9f984a12-b846-45f0-a53a-e0e58f958d5d.png)
![image](https://user-images.githubusercontent.com/79074469/127976773-a53726fb-fd49-4361-9624-f24e2d586d5b.png)

**Comment by rixo** [comment]
Customization of the View component in multiple way, somehow, is on the roadmap...

But if I understand what you need right now, this should already be covered by adding `box` prop to the current View component: `<View box ... >`.

**Comment by bhvngt** [comment]
Thanks @rixo. That worked. Closing this issue and looking forward to the future releases of this really useful project.
